"""Initial

Revision ID: cc1b3c31a5a6
Revises: 
Create Date: 2024-08-24 02:08:15.257604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1b3c31a5a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Название'),
    sa.Column('slug', sa.String(length=200), nullable=True, comment='URL'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата обновления записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False, comment='Название товара'),
    sa.Column('slug', sa.String(length=200), nullable=False, comment='URL'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание товара'),
    sa.Column('image', sa.String(length=200), nullable=True, comment='Изображение товара'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Цена товара'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество товара'),
    sa.Column('size', sa.Integer(), nullable=False, comment='Размер товара в г или мл'),
    sa.Column('calories', sa.Integer(), nullable=False, comment='Каллорий В порции, г'),
    sa.Column('protein', sa.Integer(), nullable=False, comment='Белков В порции, г'),
    sa.Column('carbohydrate', sa.Integer(), nullable=False, comment='Углеводов В порции, г'),
    sa.Column('fat', sa.Integer(), nullable=False, comment='Жиров В порции, г'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата обновления записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата обновления записи'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата обновления записи'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('product')
    op.drop_table('category')
    # ### end Alembic commands ###
